version: '2'
services:
  moonshine2_webserver_local:
    build: ./node
    container_name: moonshine2.webserver.local
    domainname: moonshine2.local
    restart: always
    ports:
     - "3333:3333"
    volumes:
     - /home/html/moonshine2:/usr/src/app
    depends_on:
     - moonshine2_mongo_local
    networks:
      moonshine_docker_local:
         ipv4_address: 10.10.0.3
    links:
     - moonshine2_mongo_local
     - moonshine2_contents_local
     - moonshine2_mongo_local:q-devbd-1.cloudapp.net
  
  moonshine2_contents_local:
    build: ./contents
    container_name: moonshine2.contents.local
    domainname: moonshine2.contents.local
    restart: always
    ports:
     - "1234:1234"
     - "30000:30000"
    volumes:
     - /home/docker_volumes/entornos/local/local_contents/images:/var/www/html/images
     - /home/docker_volumes/entornos/local/local_contents/documents:/var/www/html/documents
     - /home/docker_volumes/entornos/local/local_contents/conf:/etc/nginx/conf.d
    networks:
      moonshine_docker_local:
         ipv4_address: 10.10.0.6
    links:     
     - moonshine2_mongo_local
     - moonshine2_mongo_local:q-devbd-1.cloudapp.net  
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/contents.local > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  moonshine2_mongo_local:
    build: ./mongo
    container_name: moonshine2.mongo.local
    domainname: moonshine2.mongo.local
    restart: always
    ports:
     - "27017:27017"
    networks:
      moonshine_docker_local:
         ipv4_address: 10.10.0.2
    volumes:
     - "/home/docker_volumes/entornos/local/local_mongo:/data/db"

  moonshine2_nginx_local:
    image: nginx
    restart: always
    container_name: moonshine2.nginx.local
    links:
     - moonshine2_webserver_local
     - moonshine2_contents_local
     - moonshine2_mongo_local
     - moonshine2_mongo_local:q-devbd-1.cloudapp.net
    volumes:
     - /home/docker_volumes/entornos/local/local_nginx:/etc/nginx/conf.d
    ports:
     - "8080:80"
    networks:
      moonshine_docker_local:
         ipv4_address: 10.10.0.4
    environment:
     - NGINX_HOST=moonshine2.local
     - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/moonshine2.local > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  moonshine_docker_local:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/25
          gateway: 10.10.0.1
