version: '2'
services:
  moonshine2_webserver_dev:
    build: ./node
    container_name: moonshine2.webserver.dev
    domainname: moonshine2.dev
    ports:
     - "3333:3333"
    #volumes:
    # - /home/html/moonshine2:/usr/src/app
    depends_on:
     - moonshine2_mongo_dev
    networks:
      moonshine_docker_dev:
         ipv4_address: 10.10.1.3
    links:
     - moonshine2_mongo_dev
     - moonshine2_mongo_dev:q-devbd-1.cloudapp.net

  moonshine2_mongo_dev:
    build: ./mongo
    container_name: moonshine2.mongo.dev
    domainname: moonshine2.mongo.dev
    ports:
     - "27017:27017"
    networks:
      moonshine_docker_dev:
         ipv4_address: 10.10.1.2
    volumes:
     - "/home/docker_volumes/entornos/dev/dev_mongo:/data/db"

  moonshine2_nginx_dev:
    image: nginx
    container_name: moonshine2.nginx.dev
    domainname: moonshine2.nginx.dev
    links:
     - moonshine2_webserver_dev
     - moonshine2_mongo_dev
     - moonshine2_mongo_dev:q-devbd-1.cloudapp.net
     - moonshine2_jenkins_dev:moonshine2_jenkins_dev
    ports:
     - "80:80"
    volumes:
     - /home/docker_volumes/entornos/dev/dev_nginx:/etc/nginx/conf.d
    networks:
      moonshine_docker_dev:
         ipv4_address: 10.10.1.4
    environment:
     - NGINX_HOST=moonshine2.dev
     - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/moonshine2.dev > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  moonshine2_jenkins_dev:
    build: ./jenkins
    container_name: moonshine2.jenkins.dev
    domainname: moonshine2.jenkins.dev
    links:
     - moonshine2_webserver_dev
     - moonshine2_mongo_dev
    volumes:
     - "/home/docker_volumes/entornos/dev/dev_jenkins:/var/jenkins_home"
     - "/home/docker_volumes/entornos/dev/dev_jenkins/docker.sock:/var/run/docker.sock"
    ports:
     - "8080:8080"
    networks:
      moonshine_docker_dev:
         ipv4_address: 10.10.1.5

networks:
  moonshine_docker_dev:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/25
          gateway: 10.10.1.1
