version: '2'
services:
  moonshine2_webserver_uat:
    build: ./node
    container_name: moonshine2.webserver.uat
    domainname: moonshine2.uat
    restart: always
    ports:
     - "3333:3333"
    #volumes:
    # - /home/html/moonshine2:/usr/src/app
    depends_on:
     - moonshine2_mongo_uat
    networks:
      moonshine_docker_uat:
         ipv4_address: 10.10.2.3
    links:
     - moonshine2_mongo_uat
     - moonshine2_mongo_uat:q-devbd-1.cloudapp.net

  moonshine2_mongo_uat:
    build: ./mongo
    container_name: moonshine2.mongo.uat
    domainname: moonshine2.mongo.uat
    restart: always
    ports:
     - "27017:27017"
    networks:
      moonshine_docker_uat:
         ipv4_address: 10.10.2.2
    volumes:
     - "/home/docker_volumes/entornos/uat/uat_mongo:/data/db"

  moonshine2_nginx_uat:
    image: nginx
    container_name: moonshine2.nginx.uat
    domainname: moonshine2.nginx.uat
    links:
     - moonshine2_webserver_uat
     - moonshine2_mongo_uat
     - moonshine2_mongo_uat:q-devbd-1.cloudapp.net
     - moonshine2_jenkins_uat:moonshine2_jenkins_uat
    ports:
     - "80:80"
    volumes:
     - /home/docker_volumes/entornos/uat/uat_nginx:/etc/nginx/conf.d
    networks:
      moonshine_docker_uat:
         ipv4_address: 10.10.2.4
    environment:
     - NGINX_HOST=moonshine2.uat
     - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/moonshine2.uat > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  moonshine2_jenkins_uat:
    image: jenkins:2.7.4
    container_name: moonshine2.jenkins.uat
    domainname: moonshine2.jenkins.uat
    links:
     - moonshine2_webserver_uat
    volumes:
     - "/home/docker_volumes/entornos/uat/uatjenkins:/var/jenkins_home"
    ports:
     - "8080:8080"
    networks:
      moonshine_docker_uat:
         ipv4_address: 10.10.2.5

networks:
  moonshine_docker_uat:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.2.0/25
          gateway: 10.10.2.1
